version: "3.9"
services:

  db-mysql-1:
    image: mysql:8.0.26
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_caba
      MYSQL_USER: db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password

secrets:
  db_password:
    file: ./secrets/db_password
  db_root_password:
    file: ./secrets/db_root_password